# 上下文初始化加载
info:
  name: lession-3-sms-interface
  
server:
  port: 9002

# 配置eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
