# 上下文初始化加载
info:
  name: lession-3-sms-interface
  
server:
  port: 9003

# 配置eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yrc_test??useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
